//
//  AWSGoogleIdentityProfile.m
//  AWSMobileHubHelper
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//

#import "AWSGoogleIdentityProfile.h"
#import <GoogleSignIn/GoogleSignIn.h>

static NSUInteger const AWSGoogleSignInProviderProfileImageDimension = 150;

@interface AWSGoogleIdentityProfile()

@property (nonatomic, readwrite, nullable) NSURL *imageURL;
@property (nonatomic, readwrite, nullable) NSString *userName;

@end

@implementation AWSGoogleIdentityProfile

NSMutableDictionary<NSString *, id> *identityProfileDict = nil;
@synthesize userName;
@synthesize imageURL;

+ (instancetype)sharedInstance {
    static AWSGoogleIdentityProfile *_sharedGoogleIdentityProfile = nil;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        _sharedGoogleIdentityProfile = [[AWSGoogleIdentityProfile alloc] init];
        identityProfileDict = [[NSMutableDictionary alloc] init];
    });
    
    return _sharedGoogleIdentityProfile;
}

-(NSString *)userName {
    return userName;
}

-(NSURL *)imageURL {
    return imageURL;
}

-(void)setProfileAttribute:(id)value
                    forKey:(NSString *)key {
    [identityProfileDict setObject:value
                            forKey:key];
}

-(id)getProfileAttributeForKey:(NSString *)key {
    return [identityProfileDict objectForKey:key];
}

-(NSDictionary *)getProfileAttributesMap {
    return identityProfileDict;
}

-(void)clearProfile {
    userName = nil;
    imageURL = nil;
    identityProfileDict = [[NSMutableDictionary alloc] init];
}

-(void)loadProfile {
    GIDGoogleUser *currentUser = [GIDSignIn sharedInstance].currentUser;
    userName = currentUser.profile.name;
    imageURL = [currentUser.profile imageURLWithDimension:AWSGoogleSignInProviderProfileImageDimension];
}

@end
