//
//  AWSGoogleSignInProvider.h
//  AWSGoogleSignIn
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//
#import <Foundation/Foundation.h>
#import <AWSMobileHubHelper/AWSSignInProvider.h>
#import <AWSMobileHubHelper/AWSSignInProviderApplicationIntercept.h>

NS_ASSUME_NONNULL_BEGIN

/**
 * `AWSGoogleSignInProvider` adopts the `AWSSignInProvider` protocol.
 *
 * It works with the Google Sign In SDK internally and requires the Google Client ID provided by Google.
 */
@interface AWSGoogleSignInProvider : NSObject <AWSSignInProvider, AWSSignInProviderApplicationIntercept>

/**
 Fetches the shared instance for AWSGoogleSignInProvider.
 
 @return the single instance of AWSGoogleSignInProvider
 */
+ (instancetype)sharedInstance;

/**
 Sets the scopes required by the app during login.
 Defaults are openid and profile.
 */
- (void)setScopes:(NSArray *)scopes;

/**
 Sets the ViewController used for Google SignIn.
 Defaults to rootViewController in keyWindow during signin.
 */
- (void)setViewControllerForGoogleSignIn:(UIViewController *)signInViewController;

@end

NS_ASSUME_NONNULL_END
