//
//  AWSGoogleSignInButton.m
//  AWSGoogleSignIn
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//

#import "AWSGoogleSignInButton.h"
#import "AWSGoogleSignInProvider.h"

#define SPACING 10
#define HIGH_HUGGING_PRIORITY 99
#define LOW_HUGGING_PRIORITY 1

typedef void (^AWSSignInManagerCompletionBlock)(id result, AWSIdentityManagerAuthState authState, NSError *error);

static NSString *GoogleLogoImageKey = @"google-icon";
static NSString *ResourceBundle = @"AWSGoogleSignInResources";
static NSString *BundleExtension = @"bundle";

@interface AWSGoogleSignInButton()

@property (nonatomic, strong) id<AWSSignInProvider> signInProvider;

@property (nonatomic, strong) UIImageView *signInButton;
@property (nonatomic, strong) UIButton *googleButton;
@property (nonatomic, strong) UIStackView *googleStackView;
@property (nonatomic, strong) UIImageView *googleLogoImageView;

@end

@implementation AWSGoogleSignInButton

@synthesize delegate;
@synthesize buttonStyle;

- (id)initWithCoder:(NSCoder*)aDecoder {
    
    if (self = [super initWithCoder:aDecoder]) {
        [self commonInit];
    }
    return self;
}

- (id)initWithFrame:(CGRect)frame {
    if (self = [super initWithFrame:frame]) {
        [self commonInit];
    }
    return self;
}

- (void)commonInit {
    _signInProvider = [AWSGoogleSignInProvider sharedInstance];
    [self initGoogleButton];
    [self setUpButtonEffects];
    [self initStackView];
    [self initLogo];
    [self initLabel];
}

- (void)dealloc {
    @try {
        [self removeObserver:self forKeyPath:@"buttonStyle" context:nil];
    } @catch(id exception) {
        // ignore exception
    }
}

- (void)observeValueForKeyPath:(NSString *)keyPath ofObject:(id)object change:(NSDictionary *)change context:(void *)context {
    // property set
    if ([keyPath isEqualToString:@"buttonStyle"]) {
        if (self.googleButton) {
            [self.googleButton setImage:nil forState:UIControlStateNormal];
        }
        if (buttonStyle == AWSSignInButtonStyleLarge) {
            [self setupLargeGoogleButton];
        } else {
            [self setupSmallGoogleButton];
        }
        // refresh views
        [self.googleButton setNeedsDisplay];
        [self setNeedsDisplay];
    }
}

- (void)initGoogleButton {
    _googleButton = [[UIButton alloc] init];
    [self addObserver:self forKeyPath:@"buttonStyle" options:0 context:nil];
    [self.googleButton addTarget:self
                     action:@selector(logInWithProvider:)
           forControlEvents:UIControlEventTouchUpInside];
    CGRect buttonFrame = self.googleButton.frame;
    buttonFrame.size = CGSizeMake(self.frame.size.width, self.frame.size.height);
    self.googleButton.frame = buttonFrame;
    NSLog(@"Google Frame: %f %f", self.frame.size.width, self.frame.size.height);
    NSLog(@"Google Button: %f %f", self.googleButton.frame.size.width, self.googleButton.frame.size.height);
    [self addSubview:self.googleButton];
}

- (void)initLogo {
    UIImage *providerImage = [self getImageFromBundle:GoogleLogoImageKey];
    UIImageView *logoImageView = [[UIImageView alloc] initWithImage:providerImage];
    logoImageView.contentMode = UIViewContentModeScaleAspectFit;
    logoImageView.exclusiveTouch = NO;
    logoImageView.userInteractionEnabled = NO;
    [self.googleStackView addArrangedSubview:logoImageView];
}

-(void)initStackView {
    _googleStackView = [[UIStackView alloc] initWithFrame:self.googleButton.frame];
    self.googleStackView.axis = UILayoutConstraintAxisHorizontal;
    self.googleStackView.distribution = UIStackViewDistributionEqualSpacing;
    self.googleStackView.contentMode = UIViewContentModeScaleAspectFit;
    self.googleStackView.alignment = UIStackViewAlignmentCenter;
    self.googleStackView.layoutMargins = UIEdgeInsetsMake(SPACING, SPACING, SPACING, SPACING);
    [self.googleStackView setLayoutMarginsRelativeArrangement:YES];
    [self.googleStackView setSpacing:SPACING];
    self.googleStackView.exclusiveTouch = NO;
    self.googleStackView.userInteractionEnabled = NO;
    [self.googleButton addSubview:self.googleStackView];
}

- (void)initLabel {
    _textLabel = [[UILabel alloc] init];
    self.textLabel.numberOfLines = 1;
    self.textLabel.adjustsFontSizeToFitWidth = YES;
    self.textLabel.text = @"Sign in with Google";
    self.textLabel.font = [UIFont fontWithName:@"Helvetica-Bold" size:18];
    self.textLabel.textColor = [UIColor darkGrayColor];
    self.textLabel.exclusiveTouch = NO;
    self.textLabel.userInteractionEnabled = NO;
    [self.textLabel setContentHuggingPriority:HIGH_HUGGING_PRIORITY forAxis:UILayoutConstraintAxisHorizontal];
}

- (void)setUpButtonEffects {
    self.googleButton.backgroundColor = [UIColor whiteColor];
    self.googleButton.layer.cornerRadius = 4.0f;
    self.googleButton.layer.borderWidth = 0.1f;
    self.googleButton.layer.borderColor = [[UIColor grayColor] CGColor];
    self.googleButton.layer.shadowColor = [[UIColor lightGrayColor] CGColor];
    self.googleButton.layer.shadowOffset = CGSizeMake(0, 2.0f);
    self.googleButton.layer.shadowOpacity = 0.5f;
    self.googleButton.layer.shadowRadius = 0.0f;
    self.googleButton.layer.masksToBounds = NO;
}

- (void)setupSmallGoogleButton {
    self.googleStackView.distribution = UIStackViewDistributionEqualCentering;
    [self.textLabel removeFromSuperview];
}

- (void)setupLargeGoogleButton {
    self.googleStackView.distribution = UIStackViewDistributionFill;
    [self.googleLogoImageView setContentHuggingPriority:LOW_HUGGING_PRIORITY forAxis:UILayoutConstraintAxisHorizontal];
    [self.googleStackView addArrangedSubview:self.textLabel];
}


- (UIImage *)getImageFromBundle:(NSString *)imageName {
    NSBundle *currentBundle = [NSBundle bundleForClass:[self class]];
    NSURL *bundleUrl = [currentBundle URLForResource:ResourceBundle withExtension:BundleExtension];
    NSBundle *imageBundle = [NSBundle bundleWithURL:bundleUrl];
    return [UIImage imageNamed:imageName
                      inBundle:imageBundle
 compatibleWithTraitCollection:nil];
}

- (void)setSignInProvider:(id<AWSSignInProvider>)signInProvider {
    self.signInProvider = signInProvider;
}

- (void)logInWithProvider:(id)sender {
    
    [[AWSSignInManager sharedInstance] loginWithSignInProviderKey:[self.signInProvider identityProviderName]
                                                completionHandler:^(id result, AWSIdentityManagerAuthState authState, NSError *error) {
                                                    [self.delegate onLoginWithSignInProvider:self.signInProvider
                                                                                      result:result
                                                                                   authState:authState
                                                                                       error:error];
                                                }];
}

@end
