//
//  AWSGoogleIdentityProfile.h
//  AWSMobileHubHelper
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//

#import <Foundation/Foundation.h>
#import <AWSMobileHubHelper/AWSIdentityProfile.h>

@interface AWSGoogleIdentityProfile : NSObject<AWSIdentityProfile>

/**
 Fetches the shared instance for AWSGoogleIdentityProfile.
 
 @return the single instance of AWSGoogleIdentityProfile
 */
+ (instancetype)sharedInstance;

@end
