//
//  AWSMSDynamicsAuthorizationManager.h
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//

#import "AWSAuthorizationManager.h"

@interface AWSMSDynamicsAuthorizationManager : AWSAuthorizationManager

/**
 * Singleton used to authorize user during OAuth2.0
 * @return the singleton
 */
+ (instancetype _Nonnull)sharedInstance;

/**
 * Customize the flow.
 *
 * @param clientID The client ID provided by Microsoft Dynamics
 * @param redirectURI The redirect URI you provided Microsoft Dynamics
 *          i.e. https://mysampleapp.amazonaws.com/msdynamics/success
 * @param resource The URL of the resource you will access
 * @return the singleton
 */
- (void)configureWithClientID:(NSString * _Nonnull)clientID
                  redirectURI:(NSString * _Nonnull)redirectURI
                     resource:(NSString * _Nonnull)resource;

/**
 * @return The token type. Available after user authorizes app.
 *         i.e. Bearer
 */
- (NSString * _Nullable)getTokenType;

/**
 * @return The resource you will access in Microsoft Dynamics.
 *         i.e. https://emhawsapps.crm.dynamics.com
 */
- (NSString * _Nullable)getResourceURL;

@end
