//
//  AWSMarketoAuthorizationManager.h
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//

#import "AWSAuthorizationManager.h"

@interface AWSMarketoAuthorizationManager : AWSAuthorizationManager

/**
 * Singleton used to authorize user for Marketo
 * @return the singleton
 */
+ (instancetype _Nonnull)sharedInstance;

/**
 * Customize the flow.
 *
 * @param clientID Client ID provided by Salesforce.
 * @param redirectURI Should be you're bundle ID or universal URL
 *          i.e. com.amazonaws.mysampleapp://salesforce/success
 *               https://mysampleapp.amazonaws.com/success
 * @return the singleton
 */
- (void)configureWithIdentityURI:(NSString * _Nonnull)identityURI
                      restApiURI:(NSString * _Nonnull)restApiURI;

/**
 * @param clientID Specify the Client ID provided by Marketo.
 *          i.e. @"abc123...-abc123...-..."
 */
- (void)setClientID:(NSString * _Nonnull)clientID;

/**
 * @param clientSecret Specify the Client Secret provided by Marketo.
 *          i.e. @"aBc123..."
 */
- (void)setClientSecret:(NSString * _Nonnull)clientSecret;

/**
 * @return The access token used for API calls
 */
- (NSString * _Nullable)getAccessToken;

/**
 * @return The identity URI used during authorization and API calls
 */
- (NSString * _Nullable)getIdentityURI;

/**
 * @return The REST API URI used during authorization and API calls
 */
- (NSString * _Nullable)getRestApiURI;

@end
