//
//  AWSQuickbooksAuthorizationManager.h
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//

#import "AWSAuthorizationManager.h"

@interface AWSQuickbooksAuthorizationManager : AWSAuthorizationManager

- (void)configureWithAPIKey:(NSString * _Nonnull)key
                redirectURI:(NSString * _Nonnull)redirectURI;

- (void)setAPISecret:(NSString * _Nonnull)secret;

- (NSString * _Nullable)getAPIKey;
- (NSString * _Nullable)getAPISecret;
- (NSString * _Nullable)getAccessToken;
- (NSString * _Nullable)getAccessTokenSecret;
- (NSString * _Nullable)getRealmID;

@end
