//
//  AWSSalesforceAuthorizationManager.h
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//

#import "AWSAuthorizationManager.h"

@interface AWSSalesforceAuthorizationManager : AWSAuthorizationManager

/**
 * Singleton used to authorize user during OAuth2.0
 * @return the singleton
 */
+ (instancetype _Nonnull)sharedInstance;

/**
 * Customize the flow.
 *
 * @param clientID Client ID provided by Salesforce.
 * @param redirectURI Should be you're bundle ID or universal URL
 *          i.e. com.amazonaws.mysampleapp://salesforce/success
 *               https://mysampleapp.amazonaws.com/success
 * @return the singleton
 */
- (void)configureWithClientID:(NSString * _Nonnull)clientID redirectURI:(NSString * _Nonnull)redirectURI;

/**
 * @return The token type. Available after user authorizes app.
 *         i.e. Bearer
 */
- (NSString * _Nullable)getTokenType;

/**
 * @return The instance Salesforce has assigned you. Available after user authorizes app.
 *         i.e. https://na15.salesforce.com/
 */
- (NSString * _Nullable)getInstanceURL;

@end
