//
//  AWSZendeskAuthorizationManager.h
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//

#import "AWSAuthorizationManager.h"

@interface AWSZendeskAuthorizationManager : AWSAuthorizationManager

/**
 * Singleton used to authorize user during OAuth2.0
 * @return the singleton
 */
+ (instancetype _Nonnull)sharedInstance;

/**
 * Customize the flow.
 *
 * @param clientID The client ID that you signed up for in Zendesk
 * @param redirectURI The redirect URI you provided Zendesk
 *          i.e. https://mysampleapp.amazonaws.com/zendesk/success
 * @param subdomain The subdomain that you signed up for in Zendesk
 */
- (void)configureWithClientID:(NSString * _Nonnull)clientID
                  redirectURI:(NSString * _Nonnull)redirectURI
                    subdomain:(NSString * _Nonnull)subdomain;

/**
 * @param scope Specify the amount of access the user would like.
 *          i.e. @"read"
 *               @"read tickets:write"
 */
- (void)setScope:(NSString * _Nonnull)scope;

/**
 * @return The token type. Available after user authorizes app.
 *         i.e. Bearer
 */
- (NSString * _Nullable)getTokenType;

/**
 * @return The subdomain that you signed up for in Zendesk.
 *         i.e. aws
 */
- (NSString * _Nullable)getSubdomain;

@end
