//
//  AWSSamlIdentityProfile.h
//  AWSMobileHubHelper
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//

#import <Foundation/Foundation.h>
#import <AWSMobileHubHelper/AWSIdentityProfile.h>

@interface AWSSamlIdentityProfile : NSObject

/**
 Fetches the shared instance for AWSFacebookIdentityProfile.
 
 @return the single instance of AWSFacebookIdentityProfile
 */
+ (instancetype)sharedInstance;

- (void)setUserName:(NSString *)userName;

- (void)setImageURL:(NSURL *)imageURL;

@end
