//
//  AWSSamlIdentityProfile.m
//  AWSMobileHubHelper
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//

#import "AWSSamlIdentityProfile.h"



@interface AWSSamlIdentityProfile()

@property (nonatomic, readwrite, nullable) NSURL *imageURL;
@property (nonatomic, readwrite, nullable) NSString *userName;

@end

@implementation AWSSamlIdentityProfile

NSMutableDictionary<NSString *, id> *identityProfileDict = nil;
@synthesize userName;
@synthesize imageURL;

+ (instancetype)sharedInstance {
    static AWSSamlIdentityProfile *_sharedSamlIdentityProfile = nil;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        _sharedSamlIdentityProfile = [[AWSSamlIdentityProfile alloc] init];
        identityProfileDict = [[NSMutableDictionary alloc] init];
    });
    
    return _sharedSamlIdentityProfile;
}

-(NSString *)userName {
    return userName;
}

-(NSURL *)imageURL {
    return imageURL;
}

-(void)setProfileAttribute:(id)value
                    forKey:(NSString *)key {
    [identityProfileDict setObject:value
                            forKey:key];
}

-(id)getProfileAttributeForKey:(NSString *)key {
    return [identityProfileDict objectForKey:key];
}

-(NSDictionary *)getProfileAttributesMap {
    return identityProfileDict;
}

-(void)clearProfile {
    userName = nil;
    imageURL = nil;
    identityProfileDict = [[NSMutableDictionary alloc] init];
}

-(void)loadProfile {
    // For Saml the attributes need to be individually loaded
}

-(void)setUserName:(NSString *)samlUserName {
    userName = samlUserName;
}

-(void)setImageURL:(NSURL *)samlImageURL {
    imageURL = samlImageURL;
}

@end

