//
//  AWSSamlSignIn.h
//  AWSSamlSignIn
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//

#import "AWSSamlSignInProvider.h"
#import "AWSSamlIdentityProfileh"
