//
//  AWSFacebookSignInButton.h
//  AWSFacebookSignIn
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//

#import <UIKit/UIKit.h>
#import <AWSMobileHubHelper/AWSSignInProvider.h>
#import <AWSMobileHubHelper/AWSSignInManager.h>
#import <AWSMobileHubHelper/AWSSignInButtonView.h>

NS_ASSUME_NONNULL_BEGIN

@interface AWSFacebookSignInButton : UIView<AWSSignInButtonView>

@property (strong, nonatomic) UILabel *textLabel;

@end

NS_ASSUME_NONNULL_END
