//
//  AWSFacebookIdentityProfile.m
//  AWSMobileHubHelper
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//

#import "AWSFacebookIdentityProfile.h"
#import <FBSDKCoreKit/FBSDKCoreKit.h>
#import <FBSDKLoginKit/FBSDKLoginKit.h>

@interface AWSFacebookIdentityProfile()

@property (nonatomic, readwrite, nullable) NSURL *imageURL;
@property (nonatomic, readwrite, nullable) NSString *userName;

@end

@implementation AWSFacebookIdentityProfile

NSMutableDictionary<NSString *, id> *facebookIdentityProfileDict = nil;
@synthesize userName;
@synthesize imageURL;

+ (instancetype)sharedInstance {
    static AWSFacebookIdentityProfile *_sharedFacebookIdentityProfile = nil;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        _sharedFacebookIdentityProfile = [[AWSFacebookIdentityProfile alloc] init];
        facebookIdentityProfileDict = [[NSMutableDictionary alloc] init];
    });
    
    return _sharedFacebookIdentityProfile;
}

-(NSString *)userName {
    return userName;
}

-(NSURL *)imageURL {
    return imageURL;
}

-(void)setProfileAttribute:(id)value
                    forKey:(NSString *)key {
    [facebookIdentityProfileDict setObject:value
                            forKey:key];
}

-(id)getProfileAttributeForKey:(NSString *)key {
    return [facebookIdentityProfileDict objectForKey:key];
}

-(NSDictionary *)getProfileAttributesMap {
    return facebookIdentityProfileDict;
}

-(void)clearProfile {
    userName = nil;
    imageURL = nil;
    facebookIdentityProfileDict = [[NSMutableDictionary alloc] init];
}

-(void)loadProfile {
    FBSDKGraphRequest *requestForImageUrl = [[FBSDKGraphRequest alloc] initWithGraphPath:@"me"
                                                                              parameters:@{@"fields" : @"picture.type(large)"}];
    [requestForImageUrl startWithCompletionHandler:^(FBSDKGraphRequestConnection *connection,
                                                     NSDictionary *result,
                                                     NSError *queryError) {
        imageURL = [NSURL URLWithString:result[@"picture"][@"data"][@"url"]];
    }];
    
    FBSDKGraphRequest *requestForName = [[FBSDKGraphRequest alloc] initWithGraphPath:@"me"
                                                                          parameters:@{@"fields": @"id, name, email"}];
    [requestForName startWithCompletionHandler:^(FBSDKGraphRequestConnection *connection,
                                                 NSDictionary *result,
                                                 NSError *queryError) {
        
        userName = result[@"name"];
    }];

}

@end
