//
//  AWSHubspotAuthorizationManager.h
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//

#import "AWSAuthorizationManager.h"

@interface AWSHubspotAuthorizationManager : AWSAuthorizationManager

/**
 * Singleton used to authorize user during OAuth2.0
 * @return the singleton
 */
+ (instancetype _Nonnull)sharedInstance;

/**
 * Customize the flow.
 *
 * @param clientID The client ID provided by Hubspot
 * @param portalID The portal ID provided by Hubspot
 * @param redirectURI The redirect URI that your app has registered
 *          i.e. https://mysampleapp.amazonaws.com/hubspot/success
 */
- (void)configureWithClientID:(NSString * _Nonnull)clientID
                     portalID:(NSString * _Nonnull)portalID
                  redirectURI:(NSString * _Nonnull)redirectURI;

/**
 * Offline Access       offline         This application can make API requests on behalf of the user when
 *                                      the user is offline (not actively using the app). You will receive
 *                                      a refresh token when the user authenticates that you can store to
 *                                      gain access to a new, valid access token programtically using the
 *                                      refresh token method.
 * Contacts Read/Write 	contacts-rw 	This application reads your contact information, as well as creates 
 *                                      new contacts, contact lists, and contact properties. It can also 
 *                                      modify existing contacts, properties, and contact lists.
 * Contacts Read-Only 	contacts-ro 	This application can read your contact information, as well as 
 *                                      information about your contact properties and contact lists.
 * Blog Read/Write      blog-rw         This application can read your blog data, including posts and 
 *                                      comments, as well as create new blog posts and comments.
 * Blog Read-Only       blog-ro         This application can read your blog data, including posts and comments.
 * Events Read/Write 	events-rw       This application can read your marketing events, as well as post 
 *                                      new ones into your HubSpot account.
 * Keywords Read/Write 	keyword-rw      This application can read your keyword data, as well as insert new 
 *                                      ones into your HubSpot account.
 *
 * @param scope Specify the amount of access the user would like.
 *          i.e. @"contacts-rw"
 *               @"contacts-rw+blog-rw"
 */
- (void)setScope:(NSString * _Nonnull)scope;

@end
