//
//  AWSMobileHubAuthorizers.h
//  AWSMobileHubAuthorizers
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//

#import "AWSAuthorizationManager.h"
#import "AWSAuthorizer.h"
#import "AWSHubspotAuthorizationManager.h"
#import "AWSMarketoAuthorizationManager.h"
#import "AWSMSDynamicsAuthorizationManager.h"
#import "AWSQuickbooksAuthorizationManager.h"
#import "AWSSalesforceAuthorizationManager.h"
#import "AWSZendeskAuthorizationManager.h"
