//
//  AWSCognitoUserPoolsIdentityProfile.h
//  AWSMobileHubHelper
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//

#import <Foundation/Foundation.h>

@interface AWSCognitoUserPoolsIdentityProfile : NSObject

/**
 Fetches the shared instance for AWSCognitoUserPoolsIdentityProfile.
 
 @return the single instance of AWSCognitoUserPoolsIdentityProfile
 */
+ (instancetype)sharedInstance;

@end
