//
//  AWSCognitoUserPoolsIdentityProfile.m
//  AWSMobileHubHelper
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//

#import "AWSCognitoUserPoolsIdentityProfile.h"
#import "AWSCognitoUserPoolsSignInProvider.h"
#import <AWSCognitoIdentityProvider/AWSCognitoIdentityProvider.h>

@interface AWSCognitoUserPoolsIdentityProfile()

@property (nonatomic, readwrite, nullable) NSURL *imageURL;
@property (nonatomic, readwrite, nullable) NSString *userName;

@end

@interface AWSCognitoUserPoolsSignInProvider()

- (AWSCognitoIdentityUserPool *)getUserPool;

@end

@implementation AWSCognitoUserPoolsIdentityProfile

NSMutableDictionary<NSString *, id> *identityProfileDict = nil;
@synthesize userName;
@synthesize imageURL;

+ (instancetype)sharedInstance {
    static AWSCognitoUserPoolsIdentityProfile *_sharedCognitoUserPoolsIdentityProfile = nil;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        _sharedCognitoUserPoolsIdentityProfile = [[AWSCognitoUserPoolsIdentityProfile alloc] init];
        identityProfileDict = [[NSMutableDictionary alloc] init];
    });
    
    return _sharedCognitoUserPoolsIdentityProfile;
}

-(NSString *)userName {
    return userName;
}

-(NSURL *)imageURL {
    return imageURL;
}

-(void)setProfileAttribute:(id)value
                    forKey:(NSString *)key {
    [identityProfileDict setObject:value
                            forKey:key];
}

-(id)getProfileAttributeForKey:(NSString *)key {
    return [identityProfileDict objectForKey:key];
}

-(NSDictionary *)getProfileAttributesMap {
    return identityProfileDict;
}

-(void)clearProfile {
    userName = nil;
    imageURL = nil;
    identityProfileDict = [[NSMutableDictionary alloc] init];
}

-(void)loadProfile {
    userName = [[AWSCognitoUserPoolsSignInProvider sharedInstance] getUserPool].currentUser.username;
}

@end

