//
//  AWSIdentityProfileManager.h
//  AWSMobileHubHelper
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//

#import <Foundation/Foundation.h>
#import "AWSIdentityProfile.h"

NS_ASSUME_NONNULL_BEGIN

@interface AWSIdentityProfileManager : NSObject

+(instancetype)sharedInstance;

-(void)registerIdentityProfile:(id<AWSIdentityProfile>)identityProfile
                forProviderKey:(NSString *)key;

-(void)loadProfileForProviderKey:(NSString *)key;

-(void)clearProfileForProviderKey:(NSString *)key;

@end

NS_ASSUME_NONNULL_END
