//
//  AWSIdentityProfileManager.h
//  AWSMobileHubHelper
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//

#import <Foundation/Foundation.h>
#import "AWSIdentityProfile.h"

NS_ASSUME_NONNULL_BEGIN

@interface AWSIdentityProfileManager : NSObject

/*
 The shared instance of AWSIdentityProfileManager.
 */
+(instancetype)sharedInstance;

/*
 Registers the specified identity profile instance with a sign in provider.
 
 @param  identityProfile    The instance of identity profile implementing `AWSIdentityProfile` protocol.
 @param  key                The sign in provider key registered AWSSignInManager
 */
-(void)registerIdentityProfile:(id<AWSIdentityProfile>)identityProfile
                forProviderKey:(NSString *)key;

/*
 Loads the profile details for identity profile instance.
 */
-(void)loadProfileForProviderKey:(NSString *)key;

/*
 Clears the profile information if loaded for idenity profile instance.
 */
-(void)clearProfileForProviderKey:(NSString *)key;

@end

NS_ASSUME_NONNULL_END
