//
//  AWSIdentityProfileManager.m
//  AWSMobileHubHelper
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//

#import "AWSIdentityProfileManager.h"

@implementation AWSIdentityProfileManager

static NSMutableDictionary<NSString *, id<AWSIdentityProfile>> *identityProfileDict = nil;

+(instancetype)sharedInstance {
    static AWSIdentityProfileManager *_sharedIdentityProfileManager = nil;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        _sharedIdentityProfileManager = [[AWSIdentityProfileManager alloc] init];
        identityProfileDict = [[NSMutableDictionary alloc] init];
    });
    
    return _sharedIdentityProfileManager;
}

-(void)registerIdentityProfile:(id<AWSIdentityProfile>)identityProfile
                forProviderKey:(NSString *)key {
    [identityProfileDict setObject:identityProfile
                            forKey:key];
    
}

-(id<AWSIdentityProfile>)getIdentityProfileForProviderKey:(NSString *)key {
    return [identityProfileDict objectForKey:key];
}

-(void)clearProfileForProviderKey:(NSString *)key {
    [[self getIdentityProfileForProviderKey:key] clearProfile];
}

-(void)loadProfileForProviderKey:(NSString *)key {
    [[self getIdentityProfileForProviderKey:key] loadProfile];
}

@end
