//
//  AWSIdentityProfile.h
//  AWSMobileHubHelper
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//

NS_ASSUME_NONNULL_BEGIN

@protocol AWSIdentityProfile<NSObject>

+(instancetype)sharedInstance;

/**
 The URL for profile image of a user.
 */
@property (nonatomic, readonly, nullable) NSURL *imageURL;

/**
 The User Name of a user.
 */
@property (nonatomic, readonly, nullable) NSString *userName;

/**
 Fetches custom stored profile attribute using specified key.
 */
-(id)getProfileAttributeForKey:(NSString *)key;

/**
 Stores custom values using specified key.
 */
-(void)setProfileAttribute:(id)value
                    forKey:(NSString *)key;

/**
 Fetches the entire identity profile attributes map.
 */
-(NSDictionary *)getProfileAttributesMap;

/**
 Clears the current profile information.
 */
-(void)clearCurrentProfile;

/**
 Loads the profile information for current signed-in user.
 */
-(void)loadCurrentProfile;

@end

NS_ASSUME_NONNULL_END
