//
//  AWSIdentityProfile.h
//  AWSMobileHubHelper
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//

NS_ASSUME_NONNULL_BEGIN

/*
 This protocol defines a list of methods and properties required to be implemented by a Identity Profile provider.
 */
@protocol AWSIdentityProfile

/*
 The shared instance for the profile provider.
 */
+(id<AWSIdentityProfile>)sharedInstance;

/**
 The URL for profile image of a user.
 */
@property (nonatomic, readonly, nullable) NSURL *imageURL;

/**
 The User Name of a user.
 */
@property (nonatomic, readonly, nullable) NSString *userName;

/**
 Fetches custom stored profile attribute using specified key.
 */
-(_Nullable id)getProfileAttributeForKey:( NSString *)key;

/**
 Stores custom values using specified key.
 */
-(void)setProfileAttribute:(id)value
                    forKey:(NSString *)key;

/**
 Fetches the entire identity profile attributes map.
 */
-(NSDictionary<NSString *,id> *)getProfileAttributesMap;

/**
 Clears the current profile information.
 */
-(void)clearProfile;

/**
 Loads the profile information for current signed-in user.
 */
-(void)loadProfile;

@end

NS_ASSUME_NONNULL_END
