//
//  AWSSignInProviderFactory.m
//  AWSMobileHubHelper
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//

#import "AWSSignInProviderFactory.h"

@implementation AWSSignInProviderFactory

static NSMutableDictionary<NSString *, id<AWSSignInProvider>> *signInProviderInfo = nil;

+(instancetype)sharedInstance {
    static AWSSignInProviderFactory *_sharedSignInProviderFactory = nil;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        _sharedSignInProviderFactory = [[AWSSignInProviderFactory alloc] init];
        signInProviderInfo = [[NSMutableDictionary alloc] init];
    });
    
    return _sharedSignInProviderFactory;
}

-(void)registerAWSSignInProvider:(id<AWSSignInProvider>)signInProvider
                          forKey:(NSString *)key {
    [signInProviderInfo setValue:signInProvider
                          forKey:key];
    
}

-(id<AWSSignInProvider>)signInProviderForKey:(NSString *)key {
    return [signInProviderInfo objectForKey:key];
}

-(NSArray<NSString *>*)getRegisterdSignInProviders {
    return [signInProviderInfo allKeys];
}

@end
