//
//  AWSUserInfo.h
//  AWSMobileHubHelper
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//

NS_ASSUME_NONNULL_BEGIN

@interface AWSUserInfo : NSObject

/**
 The URL for profile image of a user.
 */
@property (nonatomic, readwrite, nullable) NSURL *imageURL;

/**
 The User Name of a user.
 */
@property (nonatomic, readwrite, nullable) NSString *userName;

/**
 Fetches custom stored values using specified key.
 */
-(id)getAttributeForKey:(NSString *)key;

/**
 Stores custom values using specified key.
 */
-(void)setAttribute:(id)value
             forKey:(NSString *)key;

/**
 Initializer for AWSUserInfo
 */
- (instancetype)initWithUserName:(NSString *)userName
                        imageURL:(NSURL * _Nullable )imageURL;

@end

NS_ASSUME_NONNULL_END
