//
//  AWSUserInfo.h
//  AWSMobileHubHelper
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//

NS_ASSUME_NONNULL_BEGIN

@protocol AWSUserInfo <NSObject>

/**
 The URL for profile image of a user.
 */
@property (nonatomic, readonly, nullable) NSURL *imageURL;

/**
 The User Name of a user.
 */
@property (nonatomic, readonly, nullable) NSString *userName;

/**
 Fetches custom stored values using specified key.
 */
-(id)valueForKey:(NSString *)key;

@end

NS_ASSUME_NONNULL_END
