//
//  AWSMobileHubHelper.h
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//

#import "AWSContentManager.h"
#import "AWSCloudLogic.h"
#import "AWSIdentityManager.h"
#import "AWSPushManager.h"
#import "AWSFacebookSignInProvider.h"
#import "AWSGoogleSignInProvider.h"
#import "AWSUserFileManager.h"
#import "AWSSignInProviderFactory.h"
#import "AWSSAMLSignInProvider.h"
#import "AWSCognitoUserPoolsSignInProvider.h"
#import "AWSAuthorizationManager.h"
#import "AWSSalesforceAuthorizationManager.h"
#import "AWSZendeskAuthorizationManager.h"
#import "AWSMSDynamicsAuthorizationManager.h"
#import "AWSQuickbooksAuthorizationManager.h"
#import "AWSHubspotAuthorizationManager.h"
#import "AWSMarketoAuthorizationManager.h"